#ifndef _OBJECTS_H_
#define _OBJECTS_H_
//Инициализация кнопок
GButton _resize_in_(BUTTON_RESIZE_IN, BUTTON_DEBOUNCE);
GButton _resize_out_(BUTTON_RESIZE_OUT, BUTTON_DEBOUNCE);
GButton _roll_(BUTTON_ROLL, BUTTON_DEBOUNCE);
GButton _previous_clip_edit_(BUTTON_PREVIOUS_CLIP_EDIT, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _pause_start_playback_(BUTTON_PAUSE_START_PLAYBACK, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _next_clip_edit_(BUTTON_NEXT_CLIP_EDIT, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _shuttle_(BUTTON_SHUTTLE, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _jog_(BUTTON_JOG, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _scroll_(BUTTON_SCROLL, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _source_timeline_viewer_(BUTTON_SOURCE_TIMELINE_VIEWER, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _source_clip_tape_(BUTTON_SOURCE_CLIP_TAPE, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _mark_in_(BUTTON_MARK_IN, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _mark_out_(BUTTON_MARK_OUT, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _insert_(BUTTON_INSERT, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _overwrite_(BUTTON_OVERWRITE, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _replace_(BUTTON_REPLACE, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _place_on_top_(BUTTON_PLACE_ON_TOP, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _fit_to_fill_(BUTTON_FIT_TO_FILL, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _append_to_end_of_timeline_(BUTTON_APPEND_TO_END_OF_TIMELINE, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
GButton _undo_(BUTTON_UNDO, BUTTON_DEBOUNCE, BUTTON_CLICK_TIMEOUT);
//Инициализация энкодера
Encoder _rotary_encoder_(ENCODER_PHASE_A, ENCODER_PHASE_B, ENC_NO_BUTTON, TYPE2);

#endif
