#ifndef _PERIPHERY_H_
#define _PERIPHERY_H_
//Светодиоды режимов колеса
#define LED_SHUTTLE PB5
#define LED_JOG PA10
#define LED_SCROLL PA9
//Кнопки инструментов
#define BUTTON_RESIZE_IN PB9
#define BUTTON_RESIZE_OUT PB8
#define BUTTON_ROLL PB7
#define BUTTON_PREVIOUS_CLIP_EDIT PC14
#define BUTTON_PAUSE_START_PLAYBACK PC15
#define BUTTON_NEXT_CLIP_EDIT PA0
#define BUTTON_SHUTTLE PB14
#define BUTTON_JOG PB13
#define BUTTON_SCROLL PB12
#define BUTTON_SOURCE_CLIP_TAPE PA1
#define BUTTON_SOURCE_TIMELINE_VIEWER PA2
#define BUTTON_MARK_IN PA3
#define BUTTON_MARK_OUT PA4
#define BUTTON_INSERT PA5
#define BUTTON_OVERWRITE PA6
#define BUTTON_REPLACE PA7
#define BUTTON_PLACE_ON_TOP PB0
#define BUTTON_FIT_TO_FILL PB1
#define BUTTON_APPEND_TO_END_OF_TIMELINE PB10
#define BUTTON_UNDO PB11
//Фазы энкодера
#define ENCODER_PHASE_A PA8
#define ENCODER_PHASE_B PB15

#endif
